Rise-Vision/rise-playlist-new

- src/rise-playlist.js
- src/schedule.js
- test/rise-playlist-test.html
- test/schedule-test.html
- Start/stop rise-playlist schedule on "rise-presentation-play" and "rise-presentation-stop" events in host template
- Send "rise-playlist-play" and "rise-playlist-stop" events to rise-playlist-item on schedule transition
-  Embedded templates schedule should start when the host template start on "rise-presentation-play" event. 
- Playlist items should receive events on schedule transition so that rise-embedded-template elements can send "rise-presentation-play" and "rise-presentation-stop" events to the embedded templates
Tested locally with Chrome OS Player. Unit tests added.
- As the Reviewer, upon …
> Handle start/stop events

- src/rise-playlist.js
The items attribute is set with data from attributes-data.json after "rise-presentation-play". We need to start the schedule again when this happens. 
Restart schedule when items change
Tested locally on Chrome Player.
> Start schedule when items attribute is set

- src/rise-playlist.js
- src/schedule.js
- test/rise-playlist-test.html
- test/schedule-test.html
- Listen to "report-done" from playlist item child and set item as done
- Schedule should check every second until item is done
Items marked play-until-done work as expected
Tested locally on Chrome player 
> Handle playlist item PUD

- src/schedule.js
- This is not needed anymore after the transition classes where added
It was causing an issue where the playlist disappears after the first schedule transition when there is multiple items in the display schedule
Tested locally
> Remove call to hide playlist item elements when schedule stops

- src/rise-playlist.js
- src/schedule.js
- test/rise-playlist-test.html
- test/schedule-test.html
- Handle rise-components-ready event in RisePlaylistItem and set a flag indicating if item is ready or not
- Skip items that are not ready when playing the schedule
- Avoid getting stuck showing an empty state when the template is not ready
- Tested locally with Chrome player
- Unit tests added
> Handle ready event

- src/rise-playlist.js
Set width, height and display styles in rise-playlist
Make it fit the container element. This was brought up by creative when validating the component.
Tested locally. 
> Set width, height and display styles in rise-playlist

- html/index.html
- src/rise-playlist.js
- test/rise-playlist-test.html
Render preview state
Rendering the embedded templates on preview either in the template editor or when the template is running as standalone is difficult because the component depends on events that are triggered by Viewer (rise-presentation-play, rise-presentation-stop, rise-components-ready and template-done). While these events can be simulated in preview mode, the embedded templates won't render properly because they depend on data from player. 
In order to keep it consistent, the component will render an overlay similar to what rise-video does when running in preview state.
Tested locally. 
- As the …
> Render preview state

- src/rise-playlist.js
- test/rise-playlist-test.html
Fix `invalid component data` error by adding the "ID" attribute to the dynamically created elements. 
The error was caused by  <rise-playlist-item> component trying to log "start received" even [here](https://github.com/Rise-Vision/rise-common-component/blob/master/src/rise-element.js#L113), but failing the "id" check [here](https://github.com/Rise-Vision/common-template/blob/0f7237010bc5a4dc0313315860494dafacda3939/src/rise-logger.js#L203) and as a result logging a severe error instead.
Fix **severe** error.
Confirmed on local machine in Chrome inspector that error is not logged anymore.
- As the Reviewer, …
> Add ID to the dynamically created elements

- e2e/rise-playlist.html
Add static background for e2e test template
Fixes issue where Viewer background could break tests
Validated changes with the other builds.
e2e page has the expected background: http://widgets.risevision.com/beta/e2e/rise-playlist/electron/e2e/rise-playlist.html
No
> Add static background for e2e test template

- src/rise-playlist.js
- src/schedule.js
- test/schedule-test.html
Fix for use cases when "done" was not sent by playlist. Use cases:
- All items in the playlist return error. This may occur when Viewer runs without Player in the Shared Schedules mode and all embedded templates have unsupported components like Video or Financial. Fixed by adding event listener for "rise-components-error" event sent by [rise-embedded-template](https://github.com/Rise-Vision/rise-embedded-template/blob/de153fdd63838d21c78bf2541ce6206b341815de/src/rise-embedded-template.js#L141).
- All items in the playlist failed to load without error. Fixed by adding 30 seconds timeout.
- First template fails to load i.e. remain in the "not ready" state. Fixed by moving the check for the "done" condition before checking for "not ready" state.
Other improvements:
- If playlist consisted of …
> Playlist improvements

- package.json
- src/rise-playlist.js
This is part 2 of 2. Part 1 is [here](https://github.com/Rise-Vision/rise-common-component/pull/43).
Move `"rise-presentation-play"` and `"rise-presentation-stop”` event handlers from `rise-playlist-new` to `rise-common-component`. Those events are not specific to the `rise-playlist-new` only and don't belong there.
Motivated by issue https://github.com/Rise-Vision/rise-embedded-template/issues/17. The is an alternative fix for the issue. Registering event handlers before sending `"configured"` to the `common-template` [here](https://github.com/Rise-Vision/rise-common-component/compare/stage/add-play-event-handler?expand=1#diff-984deaa28b4ffc2771d3d888d97b7223R109) guarantees that `"rise-presentation-play"` event won't be missed in case if `common-template` handles `"configured"` …
> Move "rise-presentation-play" and "rise-presentation-stop” event handlers to RiseElement

- src/schedule.js
- test/schedule-test.html
Fix for issue #28 - reset transition on schedule stop. The problem occurs when there is more than one presentation in a schedule. The problem was that the playlist did not hide the last embedded presentation when it received the `stop` command from the Viewer. So, when a presentation with the playlist receives `start` command again, the playlist makes the first item visible, but a user cannot see because it's hidden under the last playlist item. The visibility of the item is controlled by Transitions, so the fix simply resets transitions when playlist is stopped.
0 defects
Visually on local machine. Tests are updated.
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been …
> Fix for issue 28 - reset transition on schedule stop

- src/schedule.js
Use setTimeout() instead of requestAnimationFrame() to change property and animate on next rendering cycle.
Playlist Component epic.
Transitions didn't work when switching tabs, causing multiple elements to be visible.
From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame): 
"requestAnimationFrame() calls are paused in most browsers when running in background tabs or hidden <iframe>s in order to improve performance and battery life."
Note: Stripes transitions worked as expected and didn't need changes.
Tested locally with Charles proxy on multiple scenarios.
- As the …
> Prevent transitions from failing to complete when switching tabs

- src/schedule.js
- test/schedule-test.html
Set 0 seconds duration for default transition (i.e. no transition).
Items were overlapping for 1 second, as it was taking 1 seconds to transition previous played element to invisible 
Playlist component epic
Tested locally, with Charles proxy
> Prevent default transition items from overlapping for 1s

- src/rise-playlist.js
- test/rise-playlist-test.html
Send RiseElement play/stop event names
Playlist Component epic.
RisePlayerConfiguration will no longer pass `rise-presentation-play`/`rise-presentation-stop` events to the components in a playlist. Hence, the playlist item can now pass events with the same name.
Tested changes locally with the proxy. Updated unit tests.
No
> Send RiseElement play/stop event names

- src/rise-playlist.js
- test/rise-playlist-test.html
Skip unsupported Shared Schedule components (i.e. rise-video)
Playlist Component epic
Videos should not play in Shared Schedules, as caching is not available yet.
They will continue to show as placeholder when running locally and in the Editor.
Tested locally with both inline and JSON/items attribute based components.
If any Release Checklist items were intentionally skipped, please provide which ones and …
> Skip unsupported Shared Schedule components (i.e. rise-video)

- README.md
Remove no longer relevant Integration section
This is no longer relevant considering templates should use rise-init
Documentation change only
> Remove no longer relevant Integration section

- package-lock.json
- package.json
- src/rise-playlist.js
- src/schedule.js
- test/schedule-test.html
- Log errors as discussed [here](https://trello.com/c/R4YelOXd/8034-uptime-error-review-playlist-component-1) and defined in the [Uptime Standards](https://docs.google.com/document/d/1fiLb4VjARw18tSweV13rOCBcFZNruV2GR4KsabQ47ww/edit#bookmark=id.eoonlddkmbm6).
[Uptime Standards](https://docs.google.com/document/d/1fiLb4VjARw18tSweV13rOCBcFZNruV2GR4KsabQ47ww/edit#bookmark=id.w4gnafd2zq1p).
- Unit tests
- Tested on local machine using Charles proxy
- Confined error "E000000108" is logged into BQ
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release …
> Log an error when all items return errors or time out

- src/rise-playlist.js
- test/rise-playlist-test.html
Set the play-until-done attribute on the element
components require the attribute to know
if they should send done or not
Playlist UI
Tested changes locally with various components. Updated unit tests.
No
> Set the play-until-done attribute on the element

- src/rise-playlist.js
- test/rise-playlist-test.html
Set the play-until-done attribute on the element (#51)
components require the attribute to know
if they should send done or not
Set element properties via polymer method (#52)
Allows object type properties to be set correctly
Convert property names to camel case
Send start event after properties are updated
Playlist UI
Tested locally with the proxy. Updated coverage.
No
> Set play-until-done and element properties via Polymer method

- src/rise-playlist.js
- test/rise-playlist-test.html
Revert "Set play-until-done and element properties via Polymer method (#50)"
This reverts commit 58683b4b0fbde06ad25531587790a18ebdc58cfb.
Fix for #55 
Revert to a previous commit.
No
> Revert "Set play-until-done and element properties via Polymer method (#50)"

- src/rise-playlist.js
- test/rise-playlist-test.html
Set element play-until-done and properties via Polymer
Set the play-until-done attribute on the element (#51)
components require the attribute to know
if they should send done or not
Set element properties via polymer method (#52)
Allows object type properties to be set correctly
Convert property names to camel case
Re-release #50 without the change that introduced #55 
Tested with the proxy and updated unit tests.
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been …
> Set element play-until-done and properties via Polymer

- README.md
Update readme to reference the allowed-components parameter
This parameter is used for Apps only, not within the component itself
Playlist UI.
Documentation update. No changes to functionality.
No
> Update readme to reference the allowed-components parameter

- src/rise-playlist.js
- test/rise-playlist-test.html
Fix placeholder not being rendered on initial presentation load. 
Also, skip placeholder rendering if playlist is non-editable.
As items was initially set as `undefined`, the placeholder conditional was not being rendered. Per polymer documentation, computed function is not invoked until at least one dependency is defined (!== undefined). So we default it to null to force computed function to be invoked.
With charles proxy, on editor and player.
Stage link: widgets.risevision.com/staging/components/rise-playlist/start-editor-rendering/rise-playlist-bundle.min.js
Sample presentation: https://apps-stage-1.risevision.com/templates/edit/084855d6-641f-4b35-87de-a1a91c5ffc92/?cid=554d3ef9-78b7-4726-8f46-c1ec140c166d
Non editable: https://apps-stage-1.risevision.com/templates/edit/d8653142-0d06-4 …
> Fix placeholder not being rendered on initial presentation load
